
int absVal(int);
int test_absVal(int);
int addOK(int, int);
int test_addOK(int, int);
int anyOddBit();
int test_anyOddBit();
int bang(int);
int test_bang(int);
int bitCount(int);
int test_bitCount(int);
int bitParity(int);
int test_bitParity(int);
int bitXor(int, int);
int test_bitXor(int, int);
int byteSwap(int, int, int);
int test_byteSwap(int, int, int);
int conditional(int, int, int);
int test_conditional(int, int, int);
int divpwr2(int, int);
int test_divpwr2(int, int);
int ezThreeFourths(int);
int test_ezThreeFourths(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
unsigned float_i2f(int);
unsigned test_float_i2f(int);
unsigned float_neg(unsigned);
unsigned test_float_neg(unsigned);
int getByte(int, int);
int test_getByte(int, int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int isEqual(int, int);
int test_isEqual(int, int);
int isNegative(int);
int test_isNegative(int);
int isNonZero(int);
int test_isNonZero(int);
int isNotEqual(int, int);
int test_isNotEqual(int, int);
int isTmax(int);
int test_isTmax(int);
int isTmin(int);
int test_isTmin(int);
int isZero(int);
int test_isZero(int);
int leastBitPos(int);
int test_leastBitPos(int);
int minusOne();
int test_minusOne();
int negate(int);
int test_negate(int);
int replaceByte(int, int, int);
int test_replaceByte(int, int, int);
int satAdd(int, int);
int test_satAdd(int, int);
int sign(int);
int test_sign(int);
int tmax();
int test_tmax();
int tmin();
int test_tmin();
int upperBits(int);
int test_upperBits(int);
